package com.urlshorty.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.time.Instant;
import java.time.temporal.ChronoUnit;

/**
 * JPA entity representing one row of the {@code short_urls} table.
 *
 * <p>One row holds the short code, the long URL it points at, the two timestamps the project
 * specification asks for, and the access counter used by the statistics endpoint.
 */
@Entity
@Table(
        name = "short_urls",
        uniqueConstraints = @UniqueConstraint(
                name = "uk_short_urls_short_code",
                columnNames = "short_code"))
public class ShortUrl {

    /** Surrogate primary key, generated by the database (identity column). */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The long URL the user submitted. */
    @Column(name = "original_url", nullable = false, length = 2048)
    private String originalUrl;

    /**
     * The short code that identifies this record, for example {@code abc123}.
     *
     * <p>The unique constraint is the real guarantee that two rows never share a code. Application
     * code checks first for a friendlier flow, but under concurrency only the database can
     * arbitrate. The constraint also creates the index that makes lookups by code fast, so no
     * separate index is declared.
     */
    @Column(name = "short_code", nullable = false, length = 16)
    private String shortCode;

    /** Creation time in UTC. Set once, never changed. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Last modification time in UTC. Refreshed on every update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** How many times this short code has been resolved through the API. */
    @Column(name = "access_count", nullable = false)
    private long accessCount;

    /** Required by JPA. Not meant to be called by application code. */
    protected ShortUrl() {
    }

    public ShortUrl(String originalUrl, String shortCode) {
        this.originalUrl = originalUrl;
        this.shortCode = shortCode;
    }

    /**
     * Lifecycle callback executed by Hibernate just before the first INSERT.
     *
     * <p>Timestamps are truncated to milliseconds. Whole seconds would match the example in the
     * project specification character for character, but an update performed in the same second as
     * the creation would then be indistinguishable from it. See docs/PROJECT_GUIDE.md, "Design
     * decisions", for the full reasoning.
     */
    @PrePersist
    void onCreate() {
        Instant now = Instant.now().truncatedTo(ChronoUnit.MILLIS);
        this.createdAt = now;
        this.updatedAt = now;
    }

    /** Lifecycle callback executed before every UPDATE. */
    @PreUpdate
    void onUpdate() {
        this.updatedAt = Instant.now().truncatedTo(ChronoUnit.MILLIS);
    }

    public Long getId() {
        return id;
    }

    public String getOriginalUrl() {
        return originalUrl;
    }

    public void setOriginalUrl(String originalUrl) {
        this.originalUrl = originalUrl;
    }

    public String getShortCode() {
        return shortCode;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    public long getAccessCount() {
        return accessCount;
    }

    public void setAccessCount(long accessCount) {
        this.accessCount = accessCount;
    }
}
