-- Reference schema for urlshorty.
--
-- You do not need to run this. The application creates its own schema from the entity
-- (ShortUrl.java) when it starts, which is what keeps the first run a single command.
--
-- The statements below are the equivalent SQL, for reading and for creating the schema by hand
-- when the MySQL profile is used or when a migration tool is introduced later.

-- ---------------------------------------------------------------- MySQL 8

CREATE TABLE short_urls
(
    id           BIGINT       NOT NULL AUTO_INCREMENT,
    original_url VARCHAR(2048) NOT NULL,
    short_code   VARCHAR(16)  NOT NULL,
    created_at   TIMESTAMP(6) NOT NULL,
    updated_at   TIMESTAMP(6) NOT NULL,
    access_count BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT pk_short_urls PRIMARY KEY (id),
    -- The guarantee that no two rows share a code. This is the constraint the application
    -- relies on when two requests generate the same code at the same moment.
    -- It also creates the index that makes lookups by short_code fast.
    CONSTRAINT uk_short_urls_short_code UNIQUE (short_code)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- MySQL also needs the database itself:
--   CREATE DATABASE urlshorty CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- --------------------------------------------------------------------- H2
-- H2 is the default profile and normally needs no manual schema at all. This is the
-- equivalent statement if you ever want to create it yourself:

-- CREATE TABLE short_urls
-- (
--     id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     original_url VARCHAR(2048) NOT NULL,
--     short_code   VARCHAR(16)  NOT NULL,
--     created_at   TIMESTAMP    NOT NULL,
--     updated_at   TIMESTAMP    NOT NULL,
--     access_count BIGINT       NOT NULL DEFAULT 0,
--     CONSTRAINT uk_short_urls_short_code UNIQUE (short_code)
-- );

-- ---------------------------------------------------------------- examples
-- Useful statements when poking at the data by hand.

-- The ten most visited short URLs.
-- SELECT short_code, original_url, access_count
-- FROM short_urls
-- ORDER BY access_count DESC
-- LIMIT 10;

-- How many links were created today.
-- SELECT COUNT(*) FROM short_urls WHERE created_at >= CURRENT_DATE;

-- The busiest hour of the day, by creation time.
-- SELECT HOUR(created_at) AS hour_of_day, COUNT(*) AS links
-- FROM short_urls
-- GROUP BY HOUR(created_at)
-- ORDER BY links DESC;
